#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hacking
Version  : 0.10.1
Release  : 1
URL      : http://tarballs.openstack.org/hacking/hacking-0.10.1.tar.gz
Source0  : http://tarballs.openstack.org/hacking/hacking-0.10.1.tar.gz
Summary  : OpenStack Hacking Guideline Enforcement
Group    : Development/Tools
License  : Apache-2.0
Requires: hacking-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
Introduction
============
hacking is a set of flake8 plugins that test and enforce the `OpenStack
Style Guidlines <http://docs.openstack.org/developer/hacking>`_.

%package python
Summary: python components for the hacking package.
Group: Default

%description python
python components for the hacking package.


%prep
%setup -q -n hacking-0.10.1

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
